services:
    shorty.repository:
        class: Allphat\Bundle\ShortyBundle\Repository\ShortyRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ Allphat\Bundle\ShortyBundle\Entity\ShortyEntity ]

    shorty.manager:
        class: Allphat\Bundle\ShortyBundle\Manager\ShortyManager
        arguments: ["@shorty.repository"]

    shorty.controller:
        class: Allphat\Bundle\ShortyBundle\Controller\ShortyController
        arguments: ["@shorty.manager"]

    shorty.shorterner:
	class: Allphat\Bundke\ShortyBundle\Shortener\Shortener
	calls:
            - method: generateRandomCode
