git:
  depth: 25

language: php

matrix:
    include:
      - php: 7.2
    fast_finish: true

before_script:
  - composer require php-coveralls/php-coveralls	
  - composer install

script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - ./vendor/bin/simple-phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

branches:
  only:
    - master

notifications:
  email:
    -  ybrigant@gmail.com

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

