<?php

namespace AppBundle\Repository;

/**
 * ShorturlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShorturlRepository extends \Doctrine\ORM\EntityRepository
{
}
