<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ShortyGeneratedEntity;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ShortyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortyGeneratedRepository extends EntityRepository
{
    /**
     * persists links in db
     *
     * @param  ShortGeneratedEntity $short [description]
     * @return [type]                [description]
     */
    public function save(ShortyGeneratedEntity $shortyGenerated)
    {
        try {
            $this->_em->persist($shortyGenerated);
            $this->_em->flush();

            return true;
        } catch (UniqueConstraintViolationException $e) {
            return false;
        }
    }


    /**
     * [findLast description]
     * @return [type] [description]
     */
    public function findLast()
    {
        $query = $this->createQueryBuilder('sg');
        $query->select('sg');
        $query->setMaxResults(1);
        $query->orderBy('sg.id', 'DESC');

        return $query->getQuery()->getResult()[0];
    }

    /**
     * [getUnusedOne description]
     * @return [type] [description]
     */
    public function findUnusedOne()
    {
        return $this->findOneBy(['is_used' => false]);
    }
}
