<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ShorturlEntity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ShorturlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShorturlRepository extends EntityRepository
{
    /**
     * persists links in db
     *
     * @param  ShorturlEntity $short [description]
     * @return [type]                [description]
     */
    public function save(ShorturlEntity $short)
    {
        $this->_em->persist($short);
        $this->_em->flush();
    }
}
