<?php

namespace Allphat\ShortyBundle\Repository;

use Allphat\ShortyBundle\Entity\ShortyEntity;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ShortyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortyRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ShortyEntity::class);
    }

    public function persist(ShortyEntity $shortyEntity): void
    {
        $this->getEntityManager()->persist($shortyEntity);
    }

    public function save(): bool
    {
        try {
            $this->getEntityManager()->flush();

            return true;
        } catch (UniqueConstraintViolationException $e) {
            return false;
        }
    }
    
    public function getByCode(string $code, bool $alllowSecureOnly): ?ShortyEntity
    {
        $query = $this->createQueryBuilder('sg');
        $query->select('sg');
        $query->andWhere('sg.code = :code');
        $query->setParameter('code', $code);
        if (!$allowSecureOnly) {
            $query->orWhere('sg.code = :insecure_code');
            $query->setParameter('insecure_code', str_replace('https','http', $code));        
        }
        
        return $query->getQuery()->getSingleResult();
    }

    public function findLast(): ?ShortyEntity
    {
        $query = $this->createQueryBuilder('sg');
        $query->select('sg');
        $query->setMaxResults(1);
        $query->orderBy('sg.id', 'DESC');

        return $query->getQuery()->getSingleResult();
    }

    public function findUnusedOne(): ?ShortyEntity
    {
        return $this->findOneBy(['is_used' => false]);
    }
}