<?php

namespace Alphat\Bundle\ShortyBundle\Repository;

use Alphat\Bundle\ShortyBundle\Entity\ShortyEntity;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ShortyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortyRepository extends EntityRepository
{
    /**
     * persists links in db
     *
     * @param  ShortyEntity $short [description]
     * @return [type]                [description]
     */
    public function save(ShortyEntity $short)
    {
        $this->_em->persist($short);
        $this->_em->flush();
    }
}

