<?php

namespace Allphat\Bundle\ShortyBundle\Repository;

use Allphat\Bundle\ShortyBundle\Entity\ShortyEntity;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ShortyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortyRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ShortyEntity::class);
    }

    /**
     * [persist description]
     * @param  ShortyEntity $shortyEntity [description]
     * @return [type]                     [description]
     */
    public function persist(ShortyEntity $shortyEntity)
    {
        $this->getEntityManager()->persist($shortyEntity);
    }


    /**
     * persists links in db
     *
     * @param  ShortyEntity $short [description]
     * @return [type]                [description]
     */
    public function save()
    {
        try {
            $this->getDoctrine()->getManager()->flush();

            return true;
        } catch (UniqueConstraintViolationException $e) {
            return false;
        }
    }


    /**
     * [findLast description]
     * @return [type] [description]
     */
    public function findLast()
    {
    	$entityManager = $this->getEntityManager();
        $query = $this->createQueryBuilder('sg');
        $query->select('sg');
        $query->setMaxResults(1);
        $query->orderBy('sg.id', 'DESC');

        return $query->getQuery()->getResult()[0];
    }

    /**
     * [getUnusedOne description]
     * @return [type] [description]
     */
    public function findUnusedOne()
    {
        return $this->findOneBy(['is_used' => false]);
    }
}

